=== NPavie/pipeline1/transformers/se_tpb_wordml2dtbook/tagset.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--W3C Schema generated by XMLSpy v2006 sp2 U (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.tpb.se/ns/2006/wml2dtbook" targetNamespace="http://www.tpb.se/ns/2006/wml2dtbook" elementFormDefault="qualified">
	<xs:element name="character">
		<xs:annotation>
			<xs:documentation>Contains all character styles that should be addressed</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tag" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Defines a style</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="comment" type="xs:string">
		<xs:annotation>
			<xs:documentation>Defines that the style should become a comment</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="custom">
		<xs:annotation>
			<xs:documentation>Defines a set of customized rules</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="paragraphs"/>
				<xs:element ref="character"/>
			</xs:sequence>
			<xs:attribute name="style" type="xs:ID" use="required">
				<xs:annotation>
					<xs:documentation>Identifies this custom set</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="map">
		<xs:complexType>
			<xs:attribute name="value" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Defines the value to map to</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="mappings">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="standardWord" maxOccurs="unbounded"/>
				<xs:element ref="custom" maxOccurs="unbounded"/>
			</xs:choice>
			<xs:attribute name="version" type="xs:string" use="required" fixed="2006-1"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="noteref" type="xs:string">
		<xs:annotation>
			<xs:documentation>Defines</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="pagenum" type="xs:string">
		<xs:annotation>
			<xs:documentation>Defines</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="paragraphs">
		<xs:annotation>
			<xs:documentation>Contains all paragraph styles that should be addressed</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tag" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="standardWord">
		<xs:annotation>
			<xs:documentation>Defines a set of default mappings to built-in Word styles</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="paragraphs"/>
				<xs:element ref="character"/>
			</xs:sequence>
			<xs:attribute name="version" use="required">
				<xs:annotation>
					<xs:documentation>Defines the version of the built-in tag set</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:byte">
						<xs:enumeration value="4"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="tag">
		<xs:annotation>
			<xs:documentation>Defines a style</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice>
				<xs:element ref="map">
					<xs:annotation>
						<xs:documentation>Defines that the style should map to the specified tag</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="wrap">
					<xs:annotation>
						<xs:documentation>Defines that the style should be wrapped in the specified tag</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="comment">
					<xs:annotation>
						<xs:documentation>Defines that the style should become a comment</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="pagenum">
					<xs:annotation>
						<xs:documentation>Defines that the style should become a pagenum</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="noteref">
					<xs:annotation>
						<xs:documentation>Defines that the style should become a noteref</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:choice>
			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Defines the style name</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="wrap">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="attribute">
					<xs:annotation>
						<xs:documentation>Defines attributes that should be added to the wrapping tag</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="value" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>Defines the attribute value</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="name" type="xs:NMTOKEN" use="required">
							<xs:annotation>
								<xs:documentation>Defines the attribute name</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="value" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Defines the tag to wrap with</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="using" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Defines the inner tag used when wrapping</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="addId" use="required">
				<xs:annotation>
					<xs:documentation>Defines if a unique id should be added to this tag</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:boolean"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="merge" use="required">
				<xs:annotation>
					<xs:documentation>Defines if consecutive styles should be merged within the same wrapping tag</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:boolean"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== NPavie/pipeline1/transformers/se_tpb_wordml2dtbook/tagsets/default-tagset.xml
<?xml version="1.0" encoding="UTF-8"?>
<mappings version="2006-1" xmlns="http://www.tpb.se/ns/2006/wml2dtbook" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.tpb.se/ns/2006/wml2dtbook tagset.xsd">
	<standardWord version="4">
		<paragraphs>
			<tag name="heading 1" listOverride="true"><map value="h1"/></tag>
			<tag name="heading 2" listOverride="true"><map value="h2"/></tag>
			<tag name="heading 3" listOverride="true"><map value="h3"/></tag>
			<tag name="heading 4" listOverride="true"><map value="h4"/></tag>
			<tag name="heading 5" listOverride="true"><map value="h5"/></tag>
			<tag name="heading 6" listOverride="true"><map value="h6"/></tag>
			<tag name="footnote text">
				<wrap value="note" addId="true" merge="false">
					<using value="p"/>
				</wrap>
			</tag>
			<!-- Indraget Stycke -->
			<tag name="Block Text">
				<wrap value="blockquote" addId="false" merge="true">
					<using value="p"/>
				</wrap>
			</tag>
			<tag name="Body Text Indent">
				<wrap value="blockquote" addId="false" merge="false">
					<using value="p"/>
				</wrap>
			</tag>
			<!-- Kommentarer -->
			<tag name="annotation text"><comment/></tag>
			<tag name="caption">
				<wrap value="imggroup" addId="false" merge="true">
					<using value="caption"/>
				</wrap>
			</tag>
		</paragraphs>
		<character>
			<tag name="Strong"><map value="strong"/></tag>
			<tag name="Emphasis"><map value="em"/></tag>
			<tag name="page number"><pagenum/></tag>
			<tag name="footnote reference"><noteref/></tag>
		</character>
	</standardWord>
</mappings>

=== NPavie/pipeline1/transformers/se_tpb_wordml2dtbook/custom-tagset.xml
<?xml version="1.0" encoding="UTF-8"?>
<mappings version="2006-1" xmlns="http://www.tpb.se/ns/2006/wml2dtbook" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.tpb.se/ns/2006/wml2dtbook tagset.xsd">
	<custom style="tpb">
		<paragraphs>
			<tag name="TPB-Titel"><map value="doctitle"/></tag>
			<tag name="TPB-FÃ¶rfattare"><map value="docauthor"/></tag>
			<tag name="TPB-Metadata"><comment/></tag>
			<tag name="TPB-Bildtext"><wrap value="imggroup" using="caption" addId="false" merge="true"/></tag>
			<tag name="TPB-Poem"><wrap value="poem" using="line" addId="false" merge="true"/></tag>
			<tag name="TPB-Parallelltext">
				<wrap value="sidebar" using="p" addId="false" merge="true">
					<attribute name="render" value="optional"/>
				</wrap>
			</tag>
			<!--  -->
			<tag name="Body Text Indent"><wrap value="blockquote" using="p" addId="false" merge="true"/></tag>
			<tag name="List">
				<wrap value="list" using="li" addId="false" merge="true">
					<attribute name="type" value="pl"/>
				</wrap>
			</tag>
		</paragraphs>
		<character>
			<tag name="TPB-Sidnummer"><pagenum/></tag>
		</character>
	</custom>
</mappings>

=== NPavie/pipeline1/transformers/se_tpb_wordml2dtbook/tagsets/custom-tagset.xml
<?xml version="1.0" encoding="UTF-8"?>
<mappings version="2006-1" xmlns="http://www.tpb.se/ns/2006/wml2dtbook" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.tpb.se/ns/2006/wml2dtbook tagset.xsd">
	<custom style="default">
		<paragraphs>
			<tag name="example">
				<map value="p"/>
			</tag>
		</paragraphs>
		<character useInlineFormatting="true"/>
	</custom>
	<custom style="native">
		<paragraphs>
			<tag name="example">
				<map value="p"/>
			</tag>
		</paragraphs>
		<character useInlineFormatting="true"/>
	</custom>
	<custom style="scanned">
		<paragraphs>
			<tag name="example">
				<map value="p"/>
			</tag>
			<tag name="footnote text">
				<wrap value="note" addId="true" merge="false">
					<using value="p"/>
				</wrap>
			</tag>
		</paragraphs>
		<character useInlineFormatting="true">
			<tag name="footnote reference"><noteref/></tag>
		</character>
	</custom>
</mappings>

=== NPavie/pipeline1/transformers/se_tpb_wordml2dtbook/custom/se_tpb_custom-tagset.xml
<?xml version="1.0" encoding="UTF-8"?>
<mappings version="2006-1" xmlns="http://www.tpb.se/ns/2006/wml2dtbook" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.tpb.se/ns/2006/wml2dtbook ../tagsets/tagset.xsd">
	<custom style="tpb-default">
		<paragraphs>
			<!-- DTBookmallen -->
			<tag name="Annotationstext">
				<wrap value="annotation" addId="true" merge="false">
					<using value="p"/>
				</wrap> 
			</tag>
			<tag name="Bild">
				<map value="imggroup"/>
			</tag>
			<tag name="Bildbeskrivning">
				<wrap value="prodnote" merge="true" addId="false">
					<using value="p"/>
					<attribute name="render" value="optional"/>
				</wrap>
			</tag>
			<tag name="Bildtext">
				<wrap value="caption" addId="false" merge="true">
					<using value="p"/>
				</wrap>
			</tag>
			<tag name="Citat">
				<wrap value="blockquote" addId="false" merge="true">
					<using value="p"/>
				</wrap>
			</tag>
			<tag name="Dikt">
				<wrap value="poem" addId="false" merge="true">
					<using value="line"/>
				</wrap>
			</tag>
			<tag name="Författare"><map value="docauthor"/></tag>
			<tag name="Sidebar">
				<wrap value="sidebar" addId="false" merge="true">
					<using value="p"/>
					<attribute name="render" value="optional"/>
				</wrap>
			</tag>
			<tag name="Tabelltext">
				<wrap value="caption" addId="false" merge="true">
					<using value="p"/>
				</wrap>
			</tag>
			<tag name="Titel"><map value="doctitle"/></tag>
			<!-- / DTBookmallen -->
			
			<tag name="TPB-Titel"><map value="doctitle"/></tag>
			<tag name="TPB-Författare"><map value="docauthor"/></tag>
			<tag name="TPB-Metadata"><comment/></tag>
			<tag name="TPB-Bildtext">
				<wrap value="imggroup" addId="false" merge="true">
					<using value="caption"/>
				</wrap>
			</tag>
			<tag name="TPB-Poem">
				<wrap value="poem" addId="false" merge="true">
					<using value="line"/>
				</wrap>
			</tag>
			<tag name="TPB-Parallelltext">
				<wrap value="sidebar" addId="false" merge="true">
					<using value="p"/>
					<attribute name="render" value="optional"/>
				</wrap>
			</tag>
			<!--  -->
			<tag name="Body Text Indent">
				<wrap value="blockquote" addId="false" merge="true">
					<using value="p"/>
				</wrap>
			</tag>
			<tag name="List" listOverride="false">
				<wrap value="list" addId="false" merge="true">
					<using value="li"/>
					<attribute name="type" value="ol"/>
				</wrap>
			</tag>
		</paragraphs>
		<character useInlineFormatting="true">
			<tag name="footnote reference"><noteref/></tag>
			<!-- DTBookmallen -->
			<tag name="Annotationsreferens">
				<map value="annoref">
					<attribute name="idref" value=""/>
				</map>
			</tag>
			<tag name="Sub">
				<map value="sub"/>
			</tag>
			<tag name="Sup">
				<map value="sup"/>
			</tag>
			<tag name="Sidnummer-TPB"><pagenum/></tag>
			<!-- / DTBookmallen -->
			<tag name="TPB-Sidnummer"><pagenum/></tag>
		</character>
	</custom>
	<custom style="tpb-sit">
		<paragraphs>
			<tag name="Body Text Indent"><map value="p"/></tag>
		</paragraphs>
		<character useInlineFormatting="true"/>
	</custom>
</mappings>
